# Require the AWS provider plugin
require 'vagrant-aws'

# Require YAML module
require 'yaml'

cred = YAML.load_file('aws_creds.yaml')

# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "dummy"
  config.vm.provision :shell, path: "bootstrap.sh"

  # Specify VirtualBox provider configuration
  config.vm.provider 'virtualbox' do |vb, override|
    override.vm.box = 'ubuntu/xenial64'

  end

  # Specify AWS configuration
  config.vm.provider :aws do |aws, override|
    aws.access_key_id = cred['aws']['access_key_id']
    aws.secret_access_key = cred['aws']['secret_access_key']
    aws.region = "us-east-1"
    aws.security_groups = ['launch-wizard-1']
    aws.keypair_name = "data_eng_ec2"

    aws.ami = "ami-f4cc1de2"
    aws.instance_type = "t2.micro"
    override.ssh.username = "ubuntu"
    override.ssh.private_key_path = "aws.pem"
  end

end
